spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: order-client
server:
  port: 8008
feign:
  hystrix:
    enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
